server:
  port: ${customePort:8091}

spring:
  application:
    name: AuthService

  session:
    store-type: redis
    timeout: ${session_timeout:5m}
    redis:
      save-mode: always
      flush-mode: immediate

  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}

  data:
    mongodb:
      uri: ${mongodb_uri}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone:  ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}



